#ifndef LIB4JFORMATS_H
#define LIB4JFORMATS_H

#define L4JF_MAJOR_VERSION 0
#define L4JF_MINOR_VERSION 0
#define L4JF_PATCH_VERSION 1

#define L4JF_VERSION "lib4jformat v" + L4JF_MAJOR_VERSION + "." + L4JF_MINOR_VERSION + "." L4JF_PATCH_VERSION

#endif
